# -*- coding: utf-8 -*-
"""streamlit_run.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RGvVLyJlzSbtBImOz_0tNpS9Dgoq_RzR
"""

# !pip install streamlit

# from google.colab import drive
# drive.mount('/content/drive')
# %cd "/content/drive/MyDrive/Colab Notebooks/streamlit/"

# !wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
# !unzip ngrok-stable-linux-amd64.zip

get_ipython().system_raw('./ngrok http 8501 &')

!curl -s http://localhost:4040/api/tunnels | python3 -c \
    'import sys, json; print("Execute the next cell and the go to the following URL: " +json.load(sys.stdin)["tunnels"][0]["public_url"])'

# !streamlit run "/content/drive/MyDrive/Colab Notebooks/streamlit/streamlit_practice.py"
!streamlit run "https://github.com/vikaskftpl/streamlit/blob/main/streamlit_practice.py"





